baseURL = "https://minuk.dev/"
languageCode = "ko-kr"
title = "minuk.dev"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Min-Uk.Lee"
    description = "개발 위키와 기타 모음"
    githubUsername = "minuk-dev"
    accent = "#00a3d2"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "cpp", "c", "javascript", "typescript", "bash"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/wiki/"
    name = "Wiki"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 5
